[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "postgres" ] }
tokio = { version = "1.21.0", features = ["full"] }
lazy_static = "1.4.0"
tracing = "0.1.35"
futures-util = "0.3.20"
tracing-subscriber = "0.3.15"
toml = "0.5.9"
anyhow = "1.0.65"
thiserror = "1.0.37"
serde = {version = "1.0.140"}
serde_derive = "1.0.145"
chrono = {version = "0.4.22", features = ["serde"]}
