log_level = "info"

[server]
# the format should be version 6, and [::1]:<port> means only accept connections from localhost,
# [::]:<port> means the server can accept remote connections.
service_address = "0.0.0.0:11130"
key_path = "<path>/prim/server/cert/localhost-server.key"
cert_path = "<path>/prim/server/cert/localhost-server.crt"

[redis]
# make sure you have up a redis cluster, for auto run, please see folder "redis-cluster"
addresses = ["127.0.0.1:16379", "127.0.0.1:16380", "127.0.0.1:16381"]

[rpc]
address = "0.0.0.0:11230"
key_path = "<path>/prim/server/cert/localhost-server.key"
cert_path = "<path>/prim/server/cert/localhost-server.crt"

[rpc.scheduler]
addresses = ["127.0.0.1:11250"]
domain = "localhost"
# notion: here is .pem file
cert_path = "<path>/prim/server/cert/PrimRootCA.crt"

[sql]
address = "127.0.0.1:5432"
database = "prim"
username = "prim"
password = "prim123456"
max_connections = 100