log_level = "info"

[server]
# the format should be version 6, and [::1]:<port> means only accept connections from localhost,
# [::]:<port> means the server can accept remote connections.
service_address = "[fdb8:4587:20cd:4912:148e:4512:7391:b78f]:11130"
domain = "local-ip1"
cert_path = "/Users/slma/RustProjects/prim/server/cert/env1/local-ip1.cert.der"
key_path = "/Users/slma/RustProjects/prim/server/cert/env1/local-ip1.key.der"

[redis]
# make sure you have up a redis cluster, for auto run, please see folder "redis-cluster"
addresses = ["127.0.0.1:16379", "127.0.0.1:16380", "127.0.0.1:16381"]

# addresses of scheduler-cluster
[scheduler]
addresses = ["[fdb8:4587:20cd:4912:148e:4512:7391:b78f]:11220"]
domain = "local-ip1"
cert_path = "/Users/slma/RustProjects/prim/server/cert/env1/local-ip1.cert.der"

[rpc]
address = "[fdb8:4587:20cd:4912:148e:4512:7391:b78f]:11230"
key_path = "/Users/slma/RustProjects/prim/server/cert/env1/local-ip1.key.pem"
cert_path = "/Users/slma/RustProjects/prim/server/cert/env1/local-ip1.cert.pem"

[rpc.scheduler]
addresses = ["[fdb8:4587:20cd:4912:148e:4512:7391:b78f]:11250"]
domain = "local-ip1"
# notion: here is .pem file
cert_path = "/Users/slma/RustProjects/prim/server/cert/env1/local-ip1.cert.pem"

[sql]
address = "127.0.0.1:5432"
database = "prim"
username = "prim"
password = "prim123456"
max_connections = 100