log_level = "info"

[server]
ip_version = "v4"
public_service = true
cluster_address = "message.prim:11120"
service_address = "message.prim:11122"
domain = "localhost"
cert_path = "/prim/cert/localhost-server.crt.der"
key_path = "/prim/cert/localhost-server.key.der"
max_connections = 50000

# configuration for quic transport, can be treated as configuration for connection between ends.
[transport]
# in milliseconds
# should be set on clients
keep_alive_interval = 1000
# in milliseconds, 5*keep_alive_interval
# disconnected for such time will kill the connection.
connection_idle_timeout = 5000
max_bi_streams = 8
max_uni_streams = 8

[scheduler]
address = "scheduler.prim:11222"
domain = "localhost"
cert_path = "/prim/cert/PrimRootCA.crt.der"

[redis]
# make sure you have up a redis cluster, for auto run, please see folder "redis-cluster"
addresses = ["26379.redis:26379", "26380.redis:26380", "26381.redis:26381"]

[rpc.api]
address = "api.prim:11330"
domain = "localhost"
# notion: here is .pem file
cert_path = "/prim/cert/PrimRootCA.crt"

[rpc.scheduler]
address = "scheduler.prim:11230"
domain = "localhost"
# notion: here is .pem file
cert_path = "/prim/cert/PrimRootCA.crt"

[seqnum]
cert_path = "/prim/cert/PrimRootCA.crt.der"

[message_queue]
address = "single.kafka:9092"