log_level = "info"

[server]
# the format should be version 6, and [::1]:<port> means only accept connections from localhost,
# [::]:<port> means the server can accept remote connections.
cluster_address = "0.0.0.0:11120"
service_address = "0.0.0.0:11122"
# the address of the server, used for client to connect to.
cluster_ip = "127.0.0.1"
service_ip = "127.0.0.1"
domain = "localhost"
cert_path = "<path>/prim/server/cert/localhost-server.crt.der"
key_path = "<path>/prim/server/cert/localhost-server.key.der"
max_connections = 50000

# the setting blow will have some impact on the performance
# the rule to set those values is 'measure possible meanwhile-connection of you business and the memory you have'.
[performance]
# use if receiver slower than sender
max_sender_side_channel_size = 4096
# use if receiver faster than sender
max_receiver_side_channel_size = 256

# configuration for quic transport, can be treated as configuration for connection between ends.
[transport]
# in milliseconds
# should be set on clients
keep_alive_interval = 1000
# in milliseconds, 5*keep_alive_interval
# disconnected for such time will kill the connection.
connection_idle_timeout = 5000
max_bi_streams = 8
max_uni_streams = 8

[redis]
# make sure you have up a redis cluster, for auto run, please see folder "redis-cluster"
addresses = ["127.0.0.1:16379", "127.0.0.1:16380", "127.0.0.1:16381"]

# addresses of scheduler-cluster
[scheduler]
address = "127.0.0.1:11151"
domain = "localhost"
cert_path = "<path>/prim/server/cert/PrimRootCA.crt.der"

[rpc.api]
address = "127.0.0.1:11230"
domain = "localhost"
# notion: here is .pem file
cert_path = "<path>/prim/server/cert/PrimRootCA.crt"

[rpc.scheduler]
address = "127.0.0.1:11250"
domain = "localhost"
# notion: here is .pem file
cert_path = "<path>/prim/server/cert/PrimRootCA.crt"

[seqnum]
cert_path = "<path>/prim/server/cert/PrimRootCA.crt.der"

[message_queue]
address = "localhost:9092,localhost:9093,localhost:9094"