[workspace]
resolver = "2"

members = [
    "./lib",
    "./lib-net-tokio",
    "./lib-net-monoio",
    "./common",
    "./api",
    "./mock",
    "./seqnum",
    "./message",
    "./scheduler",
    "./msglogger",
    "./msgprocessor"
]
