version: "3.8"

services:
  26379.redis:
    image: redis:7-alpine
    container_name: redis-26379
    restart: always
    ports:
      - "26379:26379"
    networks:
      - prim
    volumes:
      - ./redis-cluster/26379/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/26379/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  26380.redis:
    image: redis:7-alpine
    container_name: redis-26380
    restart: always
    ports:
      - "26380:26380"
    networks:
      - prim
    volumes:
      - ./redis-cluster/26380/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/26380/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  26381.redis:
    image: redis:7-alpine
    container_name: redis-26381
    restart: always
    ports:
      - "26381:26381"
    networks:
      - prim
    volumes:
      - ./redis-cluster/26381/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/26381/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-cluster-meet:
    depends_on:
      - 26379.redis
      - 26380.redis
      - 26381.redis
    image: redis:7-alpine
    container_name: redis-cluster-meet
    networks:
      - prim
    volumes:
      - ./redis-cluster/docker-cluster.sh:/cmd.sh
    command:
      - sh
      - /cmd.sh
  # todo timezone setup on init
  postgres.db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - APP_DB_NAME=prim
      - APP_DB_USER=prim
      - APP_DB_PASSWORD=prim123456
    ports:
      - "15432:5432"
    networks:
      - prim
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  19092.kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "19092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@19092.kafka:9093,1@19093.kafka:9093,2@19094.kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - ./kafka-cluster/19092:/bitnami/kafka
    tty: true
    networks:
      - prim
  19093.kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "19093:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@19092.kafka:9093,1@19093.kafka:9093,2@19094.kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - ./kafka-cluster/19093:/bitnami/kafka
    tty: true
    networks:
      - prim
  19094.kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "19094:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@19092.kafka:9093,1@19093.kafka:9093,2@19094.kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - ./kafka-cluster/19094:/bitnami/kafka
    tty: true
    networks:
      - prim
  scheduler.prim:
    depends_on:
      - redis-cluster-meet
    image: prim/scheduler-amd64-linux:latest
    networks:
      - prim
    ports:
      - "11220:11220"
      - "11222:11222"
      - "11230:11230"
    tty: true
    restart: always
  seqnum.prim:
    depends_on:
      - scheduler.prim
    image: prim/seqnum-amd64-linux:latest
    networks:
      - prim
    ports:
      - "11420:11420"
    restart: always
    tty: true
  api.prim:
    depends_on:
      - scheduler.prim
    image: ghcr.io/suancaiyv/prim/api-amd64-linux:latest
    networks:
      - prim
    ports:
      - "11320:11320"
      - "11330:11330"
    tty: true
    restart: always
  message.prim:
    depends_on:
      - scheduler.prim
    image: prim/message-amd64-linux:latest
    networks:
      - prim
    ports:
      - "11122:11122"
      - "11120:11120"
    restart: always
    tty: true
networks:
  prim:
    driver: bridge