version: "3.8"

services:
  redis-16379:
    image: redis:7-alpine
    container_name: redis-16379
    restart: always
    network_mode: host
    volumes:
      - ./redis-cluster/16379/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/16379/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-16380:
    image: redis:7-alpine
    container_name: redis-16380
    restart: always
    network_mode: host
    volumes:
      - ./redis-cluster/16380/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/16380/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-16381:
    image: redis:7-alpine
    container_name: redis-16381
    restart: always
    network_mode: host
    volumes:
      - ./redis-cluster/16381/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/16381/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-cluster-meet:
    depends_on:
      - redis-16379
      - redis-16380
      - redis-16381
    image: redis:7-alpine
    container_name: redis-cluster-meet
    network_mode: host
    volumes:
      - ./redis-cluster/docker-cluster.sh:/cmd.sh
    command:
      - sh
      - /cmd.sh
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - APP_DB_NAME=prim
      - APP_DB_USER=prim
      - APP_DB_PASSWORD=prim123456
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  scheduler:
    depends_on:
      - redis-cluster-meet
    image: prim:scheduler
    network_mode: host
    tty: true
  recorder:
    depends_on:
      - scheduler
      - postgres
    image: prim:recorder
    network_mode: host
    tty: true
  api:
    depends_on:
      - scheduler
      - recorder
    image: prim:api
    network_mode: host
    tty: true
  message:
    depends_on:
      - scheduler
      - recorder
    image: prim:message
    network_mode: host
    tty: true