[package]
name = "seqnum"
version = "0.1.0"
edition = "2021"

[features]
default = []
# use tokio as file operator
# tokio_append = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = {path = "../lib", version = "0.1.0"}
lib-net-monoio = { path = "../lib-net-monoio", version = "0.1.0", features = [] }
common = { path = "../common", version = "0.1.0" }
monoio = {version = "0.1.4", features = []}
