[package]
name = "seqnum"
version = "0.1.0"
edition = "2021"

[features]
default = []
# use tokio as file operator
# tokio_append = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-net-tokio = { path = "../lib-net-tokio", version = "0.1.0", features = [] }
common = { path = "../common", version = "0.1.0" }
tokio = { version = "1.20.0", features = ["full"] }
monoio = {version = "0.1.4", features = []}
redis = { version = "0.21.0", features = ["tokio-comp", "cluster"] }
redis_cluster_async = "0.7.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.87"
tracing = "0.1.35"
futures-util = "0.3.20"
tracing-subscriber = "0.3.15"
dashmap = "5.4.0"
quinn = "0.8.5"
anyhow = "1.0.65"
thiserror = "1.0.37"
rustls = "0.20.0"
async-trait = "0.1.57"
toml = "0.5.9"
jsonwebtoken = "8.2.0"
async-channel = "1.7.0"
ahash = "0.8.0"
lazy_static = "1.4.0"
prost = "0.11.0"
structopt = "0.3.26"
fastrand = "1.8.0"
tonic = { version = "0.8.2", features = ["tls"] }
tonic-build = "0.8.2"
byteorder = "1.4.0"
async-recursion = "1.0.4"
thread_local = "1.1.7"
futures = "0.3.28"
libc = "0.2.146"
thread-id = "4.1.0"
