log_level = "info"

[server]
ip_version = "v4"
public_service = true
cluster_address = "127.0.0.1:11220"
service_address = "127.0.0.1:11222"
domain = "localhost"
cert_path = "<path>/prim/server/cert/localhost-server.crt.der"
key_path = "<path>/prim/server/cert/localhost-server.key.der"
max_connections = 50000

# configuration for quic transport, can be treated as configuration for connection between ends.
[transport]
# in milliseconds
# should be set on clients
keep_alive_interval = 1000
# in milliseconds, 3*keep_alive_interval
# disconnected for such time will kill the connection.
connection_idle_timeout = 3000
max_bi_streams = 8
max_uni_streams = 8

[redis]
# make sure you have up a redis cluster, for auto run, please see folder "redis-cluster"
addresses = ["127.0.0.1:16379", "127.0.0.1:16380", "127.0.0.1:16381"]
passwords = ["Redis.123456", "Redis.123456", "Redis.123456"]

# addresses of balancer-cluster
[cluster]
addresses = ["127.0.0.1:11150"]
self_address = "127.0.0.1:11150"
cert_path = "<path>/prim/server/cert/localhost-server.crt.der"

[rpc]
address = "0.0.0.0:11250"
key_path = "<path>/prim/server/cert/localhost-server.key"
cert_path = "<path>/prim/server/cert/localhost-server.crt"

[rpc.api]
address = "127.0.0.1:11230"
domain = "localhost"
# notion: here is .pem file
cert_path = "<path>/prim/server/cert/PrimRootCA.crt"